# -*- coding: utf-8 -*-
"""BotBot_v6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13kJ3rQsrA98KG5rEznpCsormM1swPOMf
"""

!pip install langchain
!pip install openai

OPENAI_API_KEY = "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"  # platform.openai.com
PINECONE_API_KEY = "2aa85008-4e85-4c44-b8c9-e8d26eb3a687"  # app.pinecone.io
PINECONE_ENV = "us-east1-gcp"

from langchain.document_loaders import UnstructuredPDFLoader, OnlinePDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import TextLoader

"""Time to load the data you freak"""

# mount the drive
from google.colab import drive
drive.mount('/content/drive')

loader = TextLoader('/content/drive/MyDrive/TeamPlaybook.txt') #Text or PDF loader = UnstructuredPDFLoader

data = loader.load()

print (f'You have {len(data)} document(s) in your data')
print (f'There are {len(data[0].page_content)} characters in your document')

"""Text Split"""

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(data)

print (f'Now you have {len(texts)} documents')

"""Embed"""

from langchain.vectorstores import Pinecone
from langchain.embeddings.openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)

# initialize pinecone
pinecone.init(
    api_key=PINECONE_API_KEY,  # find at app.pinecone.io
    environment=PINECONE_ENV  # next to api key in console
)
index_name = "langchain2"

"""ChatBot"""

docsearch = Pinecone.from_texts([t.page_content for t in texts], embeddings, index_name=index_name)

from langchain.llms import OpenAI
from langchain.chains.question_answering import load_qa_chain

llm = OpenAI(temperature=0, openai_api_key=OPENAI_API_KEY)
chain = load_qa_chain(llm, chain_type="stuff")

query = "What is this team called?"
docs = docsearch.similarity_search(query, include_metadata=True)
chain.run(input_documents=docs, question=query)